metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.elasticsearch:
  hosts: ['10.105.53.50:9200']
  protocol: "http"
  username: elastic
  password: "${ELASTIC_PASSWORD}"

setup.kibana:
  host: "http://10.111.2.232:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  protocol: "http"

#---------------------------- Modules ---------------------------
metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "image"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  - module: mysql
    metricsets: ["status"]
    hosts: ["tcp(db:3306)/"]
    username: root
    password: password
